"""add currency to transactions

Revision ID: c0ca6710eec8
Revises: 6b3eee336e68
Create Date: 2026-04-29 02:13:59.492201

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c0ca6710eec8"
down_revision: Union[str, Sequence[str], None] = "6b3eee336e68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.add_column(sa.Column("currency", sa.String(), nullable=True))

    op.execute("UPDATE transaction SET currency = 'CUP' WHERE currency IS NULL")

    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.alter_column("currency", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_column("currency")

    # ### end Alembic commands ###
